# Generated by Django 4.0.3 on 2022-08-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataAtten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True, null=True)),
                ('data', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
